export interface QueryExample {
	id: string;
	label: string;
	serializedQuery: string;
}

const queryExamples: QueryExample[] = [
	{
		id: 'all-german-magazines',
		label: 'All German magazines',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q7',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P10',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q273',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-magazines',
		label: 'All magazines',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q7',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-artworks',
		label: 'All artworks',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q3',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-issues-from-umeni-magazine',
		label: 'All issues from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q11',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-issues-from-umeni-magazine-with-start-time-between-1940-and-1944',
		label: 'All issues from magazine Umění with start time between 1940 and 1944',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q11',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P31',
					propertyDataType: 'time',
					propertyValueRelation: 'more-than',
					referenceRelation: 'regardless',
					value: {
						value: '+1940-00-00T00:00:00Z',
						precision: 9,
					},
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P31',
					propertyDataType: 'time',
					propertyValueRelation: 'less-than',
					referenceRelation: 'regardless',
					value: {
						value: '+1944-00-00T00:00:00Z',
						precision: 9,
					},
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-pages-from-umeni-magazine',
		label: 'All pages from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q31',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-pages-from-specific-volume',
		label: 'All pages from specific volume',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q31',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q331336',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'pages-that-have-more-than-3-reproductions',
		label: 'Pages that have more than 3 reproductions',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q31',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P38',
					propertyDataType: 'quantity',
					propertyValueRelation: 'more-than',
					referenceRelation: 'regardless',
					value: {
						value: 3,
						unit: null,
					},
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'reproductions-that-have-width-less-than-500',
		label: 'Reproductions that have width less than 500',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q33',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P40',
					propertyDataType: 'quantity',
					propertyValueRelation: 'less-than',
					referenceRelation: 'regardless',
					value: {
						value: 500,
						unit: null,
					},
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 10,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-reproductions-from-umeni-magazine',
		label: 'All reproductions from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q33',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P47',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '4',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'reproduction-from-czech-magazines-with-quality-of-extraction-ok',
		label: 'Reproductions from Czech magazines with quality of extraction as "ok"',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q33',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P47',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '4',
					negate: false,
				},
				{
					propertyId: 'P10',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q17',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '5',
					negate: false,
				},
				{
					propertyId: 'P79',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q1448426',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-captions-from-umeni-magazine',
		label: 'All captions from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q37',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P47',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '4',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-captions-that-contain-text-jiri-kroha',
		label: 'All captions that contain text "JIŘÍ KROHA"',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q37',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P49',
					propertyDataType: 'monolingualtext',
					propertyValueRelation: 'contains',
					referenceRelation: 'regardless',
					value: {
						text: 'JIŘÍ KROHA',
						language: 'cs',
					},
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'artworks-of-specific-artist',
		label: 'Artworks of specific artist',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q3',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P78',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q39898',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
];

export default queryExamples;
