export interface QueryExample {
	id: string;
	label: string;
	serializedQuery: string;
}

const queryExamples: QueryExample[] = [
	{
		id: 'all-german-magazines',
		label: 'All German magazines',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q7',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P10',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q273',
					subclasses: true,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-magazines',
		label: 'All magazines',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q7',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-artworks',
		label: 'All artworks',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q3',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-issues-from-umeni-magazine',
		label: 'All issues from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q11',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: true,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-pages-from-umeni-magazine',
		label: 'All pages from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q31',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: true,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-pages-from-specific-volume',
		label: 'All pages from specific volume',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q31',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q331336',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-reproductions-from-umeni-magazine',
		label: 'All reproductions from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q33',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P47',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: true,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: true,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: true,
					conditionRelation: 'and',
					sourceConditionId: '4',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'all-captions-from-umeni-magazine',
		label: 'All captions from magazine Umění',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q37',
					subclasses: true,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P47',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: true,
					conditionRelation: 'and',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: false,
					conditionRelation: 'and',
					sourceConditionId: '2',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'regardless-of-value',
					referenceRelation: 'regardless',
					value: '',
					subclasses: true,
					conditionRelation: 'and',
					sourceConditionId: '3',
					negate: false,
				},
				{
					propertyId: 'P29',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q133056',
					subclasses: true,
					conditionRelation: 'and',
					sourceConditionId: '4',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
	{
		id: 'artworks-of-specific-artist',
		label: 'Artworks of specific artist',
		serializedQuery: JSON.stringify( {
			conditions: [
				{
					propertyId: 'P1',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q3',
					subclasses: false,
					conditionRelation: null,
					negate: false,
				},
				{
					propertyId: 'P78',
					propertyDataType: 'wikibase-item',
					propertyValueRelation: 'matching',
					referenceRelation: 'regardless',
					value: 'Q39898',
					subclasses: false,
					conditionRelation: 'and',
					negate: false,
				},
			],
			limit: 100,
			useLimit: true,
			omitLabels: false,
		} ),
	},
];

export default queryExamples;
